from scripts.routes import *

os.mkdir(f'{work_directory}\\factory')
os.mkdir(start_storage)
os.mkdir(end_storage)
os.mkdir(cocoa_oven)
os.mkdir(fat_oven)
os.mkdir(candies)
os.mkdir(chocolate_mass)
os.mkdir(dough)
os.mkdir(filling)
os.mkdir(f'{work_directory}\\factory\\fridge')
os.mkdir(candies_fridge)
os.mkdir(waffles_fridge)
os.mkdir(chocolate_fridge)
os.mkdir(f'{work_directory}\\factory\\package')
os.mkdir(candies_package)
os.mkdir(chocolate_package)
os.mkdir(waffels_package)
os.mkdir(whipping_chocolate)
os.mkdir(chocolate_bar)
os.mkdir(chocolate_forming)
os.mkdir(furnace)
os.mkdir(slicing)
os.mkdir(filling_preparation)
